spring:
  application:
    name: AuroraTracker

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: logs/auroratracker.log
  level:
    root: OFF
    com.example.auroratracker.service.TrackingService: INFO

server:
  address: 0.0.0.0
