name: Docker image build and push


on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Copy the JAR file
        run: cp build/libs/AuroraTracker-0.0.1-SNAPSHOT.jar app.jar

      - name: Build and push multi-arch image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t robinblondin/auroratracker:latest \
            --file Dockerfile \
            --push .

      - name: Call deploy hook
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: |
          payload='{"deploy":"start"}'
          sig=$(echo -n $payload | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | sed 's/^.* //')
          curl -X POST $DEPLOY_URL \
            -H "X-Hub-Signature-256: sha256=$sig" \
            -H "Content-Type: application/json" \
            -d "$payload"
