name: Docker image build and push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Copy the JAR file
        run: cp build/libs/AuroraTracker-0.0.1-SNAPSHOT.jar app.jar

      - name: Build the Docker image
        run: docker buildx build --platform linux/arm64 . --file Dockerfile -t robinblondin/auroratracker:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push the docker image
        run: docker push robinblondin/auroratracker:latest
